/**
 * @file base_de_donnee_can_he3000.h
 *
 * @brief This header file was generated by cantools version 40.7.1 Thu Nov  6 15:19:19 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef BASE_DE_DONNEE_CAN_HE3000_H
#define BASE_DE_DONNEE_CAN_HE3000_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define BASE_DE_DONNEE_CAN_HE3000_INFO_1_FRAME_ID (0x227u)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_3_FRAME_ID (0x1a7u)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_5_FRAME_ID (0x228u)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_2_FRAME_ID (0x327u)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_4_FRAME_ID (0x527u)
#define BASE_DE_DONNEE_CAN_HE3000_TRAME_CONTACT_FRAME_ID (0x80u)

/* Frame lengths in bytes. */
#define BASE_DE_DONNEE_CAN_HE3000_INFO_1_LENGTH (8u)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_3_LENGTH (1u)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_5_LENGTH (2u)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_2_LENGTH (8u)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_4_LENGTH (8u)
#define BASE_DE_DONNEE_CAN_HE3000_TRAME_CONTACT_LENGTH (8u)

/* Extended or standard frame types. */
#define BASE_DE_DONNEE_CAN_HE3000_INFO_1_IS_EXTENDED (0)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_3_IS_EXTENDED (0)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_5_IS_EXTENDED (0)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_2_IS_EXTENDED (0)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_4_IS_EXTENDED (0)
#define BASE_DE_DONNEE_CAN_HE3000_TRAME_CONTACT_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define BASE_DE_DONNEE_CAN_HE3000_INFO_1_CONTROLLER_STATUS_NEUTRE_CHOICE (0u)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_1_CONTROLLER_STATUS_FORWARD_SELECTED_CHOICE (1u)
#define BASE_DE_DONNEE_CAN_HE3000_INFO_1_CONTROLLER_STATUS_REVERSE_SELECTED_CHOICE (2u)

#define BASE_DE_DONNEE_CAN_HE3000_INFO_3_RESET_PARTIAL_ODOMETER_RESET_CHOICE (1u)

#define BASE_DE_DONNEE_CAN_HE3000_INFO_3_CAN_LOW_BATT_FLAG_STOP_TRACTION_CHOICE (1u)

/* Frame Names. */
#define BASE_DE_DONNEE_CAN_HE3000_INFO_1_NAME "Info_1"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_3_NAME "Info_3"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_5_NAME "Info_5"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_2_NAME "Info_2"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_4_NAME "Info_4"
#define BASE_DE_DONNEE_CAN_HE3000_TRAME_CONTACT_NAME "Trame_Contact"

/* Signal Names. */
#define BASE_DE_DONNEE_CAN_HE3000_INFO_1_VEHICLE_SPEED_NAME "Vehicle_Speed"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_1_TOTAL_ODOMETER_NAME "Total_Odometer"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_1_CONTROLLER_STATUS_NAME "Controller_status"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_1_BDI_PERCENTAGE_NAME "BDI_Percentage"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_3_RESET_PARTIAL_ODOMETER_NAME "Reset_partial_odometer"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_3_CAN_LOW_BATT_FLAG_NAME "CAN_Low_Batt_flag"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_5_VEHICLE_ACCELERATION_NAME "Vehicle_Acceleration"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_2_TRIP_ODOMETER_NAME "Trip_Odometer"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_2_KEYSWITCH_VOLTAGE_NAME "Keyswitch_Voltage"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_2_CURRENT_RMS_NAME "Current_RMS"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_2_FREQUENCY_NAME "Frequency"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_4_BATTERY_POWER_NAME "Battery_power"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_4_MOTOR_RPM_NAME "Motor_Rpm"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_4_MOTOR_TEMP_NAME "Motor_Temp"
#define BASE_DE_DONNEE_CAN_HE3000_INFO_4_BATT_CURRENT_NAME "Batt_Current"

/**
 * Signals in message Info_1.
 *
 * All signal values are as on the CAN bus.
 */
struct base_de_donnee_can_he3000_info_1_t {
    /**
     * Range: -32760..32760 (-3276..3276 km/h)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t vehicle_speed;

    /**
     * Range: 0..42949700000 (0..4294970000 km)
     * Scale: 0.1
     * Offset: 0
     */
    uint32_t total_odometer;

    /**
     * Range: 0..2 (0..2 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t controller_status;

    /**
     * Battery_state_of_charge
     *
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bdi_percentage;
};

/**
 * Signals in message Info_3.
 *
 * All signal values are as on the CAN bus.
 */
struct base_de_donnee_can_he3000_info_3_t {
    /**
     * Range: 0..2 (0..2 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t reset_partial_odometer;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t can_low_batt_flag;
};

/**
 * Signals in message Info_5.
 *
 * All signal values are as on the CAN bus.
 */
struct base_de_donnee_can_he3000_info_5_t {
    /**
     * Range: 0..1000 (0..1 g)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t vehicle_acceleration;
};

/**
 * Signals in message Info_2.
 *
 * All signal values are as on the CAN bus.
 */
struct base_de_donnee_can_he3000_info_2_t {
    /**
     * Range: 0..20000 (0..2000 Km)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t trip_odometer;

    /**
     * Range: 0..1050000 (0..10500 V)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t keyswitch_voltage;

    /**
     * Range: 0..100000 (0..10000 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t current_rms;

    /**
     * Range: -18000..18000 (-18000..18000 Hz)
     * Scale: 1
     * Offset: 0
     */
    int16_t frequency;
};

/**
 * Signals in message Info_4.
 *
 * All signal values are as on the CAN bus.
 */
struct base_de_donnee_can_he3000_info_4_t {
    /**
     * Range: -327670..327670 (-32767..32767 kW)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t battery_power;

    /**
     * Range: -12000..12000 (-12000..12000 rpm)
     * Scale: 1
     * Offset: 0
     */
    int16_t motor_rpm;

    /**
     * Range: -10000..30000 (-1000..3000 °C)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t motor_temp;

    /**
     * Range: -327670..327670 (-32767..32767 A)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t batt_current;
};

/**
 * Signals in message Trame_Contact.
 *
 * All signal values are as on the CAN bus.
 */
struct base_de_donnee_can_he3000_trame_contact_t {
    /**
     * Dummy signal in empty message.
     */
    uint8_t dummy;
};

/**
 * Pack message Info_1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int base_de_donnee_can_he3000_info_1_pack(
    uint8_t *dst_p,
    const struct base_de_donnee_can_he3000_info_1_t *src_p,
    size_t size);

/**
 * Unpack message Info_1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int base_de_donnee_can_he3000_info_1_unpack(
    struct base_de_donnee_can_he3000_info_1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Info_1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int base_de_donnee_can_he3000_info_1_init(struct base_de_donnee_can_he3000_info_1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t base_de_donnee_can_he3000_info_1_vehicle_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_1_vehicle_speed_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_1_vehicle_speed_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t base_de_donnee_can_he3000_info_1_total_odometer_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_1_total_odometer_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_1_total_odometer_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t base_de_donnee_can_he3000_info_1_controller_status_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_1_controller_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_1_controller_status_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t base_de_donnee_can_he3000_info_1_bdi_percentage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_1_bdi_percentage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_1_bdi_percentage_is_in_range(uint8_t value);

/**
 * Pack message Info_3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int base_de_donnee_can_he3000_info_3_pack(
    uint8_t *dst_p,
    const struct base_de_donnee_can_he3000_info_3_t *src_p,
    size_t size);

/**
 * Unpack message Info_3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int base_de_donnee_can_he3000_info_3_unpack(
    struct base_de_donnee_can_he3000_info_3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Info_3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int base_de_donnee_can_he3000_info_3_init(struct base_de_donnee_can_he3000_info_3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t base_de_donnee_can_he3000_info_3_reset_partial_odometer_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_3_reset_partial_odometer_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_3_reset_partial_odometer_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t base_de_donnee_can_he3000_info_3_can_low_batt_flag_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_3_can_low_batt_flag_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_3_can_low_batt_flag_is_in_range(uint8_t value);

/**
 * Pack message Info_5.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int base_de_donnee_can_he3000_info_5_pack(
    uint8_t *dst_p,
    const struct base_de_donnee_can_he3000_info_5_t *src_p,
    size_t size);

/**
 * Unpack message Info_5.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int base_de_donnee_can_he3000_info_5_unpack(
    struct base_de_donnee_can_he3000_info_5_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Info_5.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int base_de_donnee_can_he3000_info_5_init(struct base_de_donnee_can_he3000_info_5_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t base_de_donnee_can_he3000_info_5_vehicle_acceleration_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_5_vehicle_acceleration_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_5_vehicle_acceleration_is_in_range(int16_t value);

/**
 * Pack message Info_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int base_de_donnee_can_he3000_info_2_pack(
    uint8_t *dst_p,
    const struct base_de_donnee_can_he3000_info_2_t *src_p,
    size_t size);

/**
 * Unpack message Info_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int base_de_donnee_can_he3000_info_2_unpack(
    struct base_de_donnee_can_he3000_info_2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Info_2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int base_de_donnee_can_he3000_info_2_init(struct base_de_donnee_can_he3000_info_2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t base_de_donnee_can_he3000_info_2_trip_odometer_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_2_trip_odometer_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_2_trip_odometer_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t base_de_donnee_can_he3000_info_2_keyswitch_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_2_keyswitch_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_2_keyswitch_voltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t base_de_donnee_can_he3000_info_2_current_rms_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_2_current_rms_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_2_current_rms_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t base_de_donnee_can_he3000_info_2_frequency_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_2_frequency_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_2_frequency_is_in_range(int16_t value);

/**
 * Pack message Info_4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int base_de_donnee_can_he3000_info_4_pack(
    uint8_t *dst_p,
    const struct base_de_donnee_can_he3000_info_4_t *src_p,
    size_t size);

/**
 * Unpack message Info_4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int base_de_donnee_can_he3000_info_4_unpack(
    struct base_de_donnee_can_he3000_info_4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Info_4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int base_de_donnee_can_he3000_info_4_init(struct base_de_donnee_can_he3000_info_4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t base_de_donnee_can_he3000_info_4_battery_power_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_4_battery_power_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_4_battery_power_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t base_de_donnee_can_he3000_info_4_motor_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_4_motor_rpm_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_4_motor_rpm_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t base_de_donnee_can_he3000_info_4_motor_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_4_motor_temp_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_4_motor_temp_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t base_de_donnee_can_he3000_info_4_batt_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double base_de_donnee_can_he3000_info_4_batt_current_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool base_de_donnee_can_he3000_info_4_batt_current_is_in_range(int16_t value);

/**
 * Pack message Trame_Contact.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int base_de_donnee_can_he3000_trame_contact_pack(
    uint8_t *dst_p,
    const struct base_de_donnee_can_he3000_trame_contact_t *src_p,
    size_t size);

/**
 * Unpack message Trame_Contact.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int base_de_donnee_can_he3000_trame_contact_unpack(
    struct base_de_donnee_can_he3000_trame_contact_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Trame_Contact.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int base_de_donnee_can_he3000_trame_contact_init(struct base_de_donnee_can_he3000_trame_contact_t *msg_p);


#ifdef __cplusplus
}
#endif

#endif
