/**
 * @file ana_inputs_muxtrace.c
 *
 * @brief This source file was generated by cantools version 40.7.1 Thu Nov  6 12:29:42 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "ana_inputs_muxtrace.h"

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int ana_inputs_muxtrace_entree_analogique_14_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_14_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_14, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_14, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_14_unpack(
    struct ana_inputs_muxtrace_entree_analogique_14_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_14 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_14 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_14_init(struct ana_inputs_muxtrace_entree_analogique_14_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_14_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_14_tension_entree_14_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_14_tension_entree_14_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_14_tension_entree_14_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}

int ana_inputs_muxtrace_entree_analogique_13_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_13_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_13, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_13, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_13_unpack(
    struct ana_inputs_muxtrace_entree_analogique_13_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_13 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_13 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_13_init(struct ana_inputs_muxtrace_entree_analogique_13_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_13_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_13_tension_entree_13_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_13_tension_entree_13_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_13_tension_entree_13_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}

int ana_inputs_muxtrace_entree_analogique_12_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_12_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_12, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_12, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_12_unpack(
    struct ana_inputs_muxtrace_entree_analogique_12_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_12 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_12 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_12_init(struct ana_inputs_muxtrace_entree_analogique_12_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_12_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_12_tension_entree_12_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_12_tension_entree_12_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_12_tension_entree_12_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}

int ana_inputs_muxtrace_entree_analogique_11_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_11_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_11, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_11, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_11_unpack(
    struct ana_inputs_muxtrace_entree_analogique_11_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_11 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_11 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_11_init(struct ana_inputs_muxtrace_entree_analogique_11_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_11_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_11_tension_entree_11_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_11_tension_entree_11_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_11_tension_entree_11_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}

int ana_inputs_muxtrace_entree_analogique_10_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_10_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_10, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_10, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_10_unpack(
    struct ana_inputs_muxtrace_entree_analogique_10_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_10 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_10 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_10_init(struct ana_inputs_muxtrace_entree_analogique_10_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_10_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_10_tension_entree_10_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_10_tension_entree_10_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_10_tension_entree_10_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}

int ana_inputs_muxtrace_entree_analogique_9_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_9_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_9, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_9, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_9_unpack(
    struct ana_inputs_muxtrace_entree_analogique_9_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_9 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_9 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_9_init(struct ana_inputs_muxtrace_entree_analogique_9_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_9_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_9_tension_entree_9_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_9_tension_entree_9_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_9_tension_entree_9_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}

int ana_inputs_muxtrace_entree_analogique_8_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_8, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_8, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_8_unpack(
    struct ana_inputs_muxtrace_entree_analogique_8_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_8 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_8 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_8_init(struct ana_inputs_muxtrace_entree_analogique_8_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_8_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_8_tension_entree_8_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_8_tension_entree_8_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_8_tension_entree_8_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}

int ana_inputs_muxtrace_entree_analogique_7_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_7_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_7, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_7, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_7_unpack(
    struct ana_inputs_muxtrace_entree_analogique_7_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_7 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_7 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_7_init(struct ana_inputs_muxtrace_entree_analogique_7_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_7_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_7_tension_entree_7_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_7_tension_entree_7_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_7_tension_entree_7_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}

int ana_inputs_muxtrace_entree_analogique_6_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_6_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_6, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_6, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_6_unpack(
    struct ana_inputs_muxtrace_entree_analogique_6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_6 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_6 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_6_init(struct ana_inputs_muxtrace_entree_analogique_6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_6_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_6_tension_entree_6_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_6_tension_entree_6_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_6_tension_entree_6_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}

int ana_inputs_muxtrace_entree_analogique_5_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_5_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_5, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_5, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_5_unpack(
    struct ana_inputs_muxtrace_entree_analogique_5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_5 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_5 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_5_init(struct ana_inputs_muxtrace_entree_analogique_5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_5_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_5_tension_entree_5_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_5_tension_entree_5_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_5_tension_entree_5_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}

int ana_inputs_muxtrace_entree_analogique_4_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_4_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_4, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_4, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_4_unpack(
    struct ana_inputs_muxtrace_entree_analogique_4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_4 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_4 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_4_init(struct ana_inputs_muxtrace_entree_analogique_4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_4_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_4_tension_entree_4_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_4_tension_entree_4_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_4_tension_entree_4_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}

int ana_inputs_muxtrace_entree_analogique_3_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_3_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_3, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_3, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_3_unpack(
    struct ana_inputs_muxtrace_entree_analogique_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_3 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_3 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_3_init(struct ana_inputs_muxtrace_entree_analogique_3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_3_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_3_tension_entree_3_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_3_tension_entree_3_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_3_tension_entree_3_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}

int ana_inputs_muxtrace_entree_analogique_2_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_2_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_2, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_2, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_2_unpack(
    struct ana_inputs_muxtrace_entree_analogique_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_2 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_2 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_2_init(struct ana_inputs_muxtrace_entree_analogique_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_2_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_2_tension_entree_2_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_2_tension_entree_2_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_2_tension_entree_2_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}

int ana_inputs_muxtrace_entree_analogique_1_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_1_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->tension_entree_1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->tension_entree_1, 0u, 0xffu);

    return (2);
}

int ana_inputs_muxtrace_entree_analogique_1_unpack(
    struct ana_inputs_muxtrace_entree_analogique_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->tension_entree_1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->tension_entree_1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int ana_inputs_muxtrace_entree_analogique_1_init(struct ana_inputs_muxtrace_entree_analogique_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ana_inputs_muxtrace_entree_analogique_1_t));

    return 0;
}

uint16_t ana_inputs_muxtrace_entree_analogique_1_tension_entree_1_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double ana_inputs_muxtrace_entree_analogique_1_tension_entree_1_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool ana_inputs_muxtrace_entree_analogique_1_tension_entree_1_is_in_range(uint16_t value)
{
    return (value <= 32000u);
}
