/**
 * @file ana_inputs_muxtrace.h
 *
 * @brief This header file was generated by cantools version 40.7.1 Thu Nov  6 12:29:42 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef ANA_INPUTS_MUXTRACE_H
#define ANA_INPUTS_MUXTRACE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_14_FRAME_ID (0x10du)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_13_FRAME_ID (0x10cu)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_12_FRAME_ID (0x10bu)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_11_FRAME_ID (0x10au)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_10_FRAME_ID (0x109u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_9_FRAME_ID (0x108u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_8_FRAME_ID (0x107u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_7_FRAME_ID (0x106u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_6_FRAME_ID (0x105u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_5_FRAME_ID (0x104u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_4_FRAME_ID (0x103u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_3_FRAME_ID (0x102u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_2_FRAME_ID (0x101u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_1_FRAME_ID (0x100u)

/* Frame lengths in bytes. */
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_14_LENGTH (2u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_13_LENGTH (2u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_12_LENGTH (2u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_11_LENGTH (2u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_10_LENGTH (2u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_9_LENGTH (2u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_8_LENGTH (2u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_7_LENGTH (2u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_6_LENGTH (2u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_5_LENGTH (2u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_4_LENGTH (2u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_3_LENGTH (2u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_2_LENGTH (2u)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_1_LENGTH (2u)

/* Extended or standard frame types. */
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_14_IS_EXTENDED (0)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_13_IS_EXTENDED (0)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_12_IS_EXTENDED (0)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_11_IS_EXTENDED (0)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_10_IS_EXTENDED (0)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_9_IS_EXTENDED (0)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_8_IS_EXTENDED (0)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_7_IS_EXTENDED (0)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_6_IS_EXTENDED (0)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_5_IS_EXTENDED (0)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_4_IS_EXTENDED (0)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_3_IS_EXTENDED (0)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_2_IS_EXTENDED (0)
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_1_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_14_NAME "Entree_Analogique_14"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_13_NAME "Entree_Analogique_13"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_12_NAME "Entree_Analogique_12"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_11_NAME "Entree_Analogique_11"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_10_NAME "Entree_Analogique_10"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_9_NAME "Entree_Analogique_9"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_8_NAME "Entree_Analogique_8"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_7_NAME "Entree_Analogique_7"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_6_NAME "Entree_Analogique_6"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_5_NAME "Entree_Analogique_5"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_4_NAME "Entree_Analogique_4"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_3_NAME "Entree_Analogique_3"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_2_NAME "Entree_Analogique_2"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_1_NAME "Entree_Analogique_1"

/* Signal Names. */
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_14_TENSION_ENTREE_14_NAME "Tension_Entree_14"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_13_TENSION_ENTREE_13_NAME "Tension_Entree_13"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_12_TENSION_ENTREE_12_NAME "Tension_Entree_12"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_11_TENSION_ENTREE_11_NAME "Tension_Entree_11"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_10_TENSION_ENTREE_10_NAME "Tension_Entree_10"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_9_TENSION_ENTREE_9_NAME "Tension_Entree_9"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_8_TENSION_ENTREE_8_NAME "Tension_Entree_8"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_7_TENSION_ENTREE_7_NAME "Tension_Entree_7"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_6_TENSION_ENTREE_6_NAME "Tension_Entree_6"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_5_TENSION_ENTREE_5_NAME "Tension_Entree_5"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_4_TENSION_ENTREE_4_NAME "Tension_Entree_4"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_3_TENSION_ENTREE_3_NAME "Tension_Entree_3"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_2_TENSION_ENTREE_2_NAME "Tension_Entree_2"
#define ANA_INPUTS_MUXTRACE_ENTREE_ANALOGIQUE_1_TENSION_ENTREE_1_NAME "Tension_Entree_1"

/**
 * Signals in message Entree_Analogique_14.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_14_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_14;
};

/**
 * Signals in message Entree_Analogique_13.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_13_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_13;
};

/**
 * Signals in message Entree_Analogique_12.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_12_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_12;
};

/**
 * Signals in message Entree_Analogique_11.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_11_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_11;
};

/**
 * Signals in message Entree_Analogique_10.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_10_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_10;
};

/**
 * Signals in message Entree_Analogique_9.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_9_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_9;
};

/**
 * Signals in message Entree_Analogique_8.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_8_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_8;
};

/**
 * Signals in message Entree_Analogique_7.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_7_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_7;
};

/**
 * Signals in message Entree_Analogique_6.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_6_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_6;
};

/**
 * Signals in message Entree_Analogique_5.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_5_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_5;
};

/**
 * Signals in message Entree_Analogique_4.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_4_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_4;
};

/**
 * Signals in message Entree_Analogique_3.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_3_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_3;
};

/**
 * Signals in message Entree_Analogique_2.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_2_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_2;
};

/**
 * Signals in message Entree_Analogique_1.
 *
 * All signal values are as on the CAN bus.
 */
struct ana_inputs_muxtrace_entree_analogique_1_t {
    /**
     * Range: 0..32000 (0..32 Volts)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t tension_entree_1;
};

/**
 * Pack message Entree_Analogique_14.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_14_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_14_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_14.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_14_unpack(
    struct ana_inputs_muxtrace_entree_analogique_14_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_14.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_14_init(struct ana_inputs_muxtrace_entree_analogique_14_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_14_tension_entree_14_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_14_tension_entree_14_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_14_tension_entree_14_is_in_range(uint16_t value);

/**
 * Pack message Entree_Analogique_13.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_13_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_13_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_13.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_13_unpack(
    struct ana_inputs_muxtrace_entree_analogique_13_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_13.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_13_init(struct ana_inputs_muxtrace_entree_analogique_13_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_13_tension_entree_13_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_13_tension_entree_13_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_13_tension_entree_13_is_in_range(uint16_t value);

/**
 * Pack message Entree_Analogique_12.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_12_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_12_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_12.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_12_unpack(
    struct ana_inputs_muxtrace_entree_analogique_12_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_12.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_12_init(struct ana_inputs_muxtrace_entree_analogique_12_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_12_tension_entree_12_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_12_tension_entree_12_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_12_tension_entree_12_is_in_range(uint16_t value);

/**
 * Pack message Entree_Analogique_11.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_11_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_11_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_11.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_11_unpack(
    struct ana_inputs_muxtrace_entree_analogique_11_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_11.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_11_init(struct ana_inputs_muxtrace_entree_analogique_11_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_11_tension_entree_11_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_11_tension_entree_11_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_11_tension_entree_11_is_in_range(uint16_t value);

/**
 * Pack message Entree_Analogique_10.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_10_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_10_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_10.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_10_unpack(
    struct ana_inputs_muxtrace_entree_analogique_10_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_10.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_10_init(struct ana_inputs_muxtrace_entree_analogique_10_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_10_tension_entree_10_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_10_tension_entree_10_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_10_tension_entree_10_is_in_range(uint16_t value);

/**
 * Pack message Entree_Analogique_9.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_9_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_9_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_9.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_9_unpack(
    struct ana_inputs_muxtrace_entree_analogique_9_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_9.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_9_init(struct ana_inputs_muxtrace_entree_analogique_9_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_9_tension_entree_9_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_9_tension_entree_9_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_9_tension_entree_9_is_in_range(uint16_t value);

/**
 * Pack message Entree_Analogique_8.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_8_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_8_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_8.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_8_unpack(
    struct ana_inputs_muxtrace_entree_analogique_8_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_8.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_8_init(struct ana_inputs_muxtrace_entree_analogique_8_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_8_tension_entree_8_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_8_tension_entree_8_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_8_tension_entree_8_is_in_range(uint16_t value);

/**
 * Pack message Entree_Analogique_7.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_7_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_7_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_7.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_7_unpack(
    struct ana_inputs_muxtrace_entree_analogique_7_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_7.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_7_init(struct ana_inputs_muxtrace_entree_analogique_7_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_7_tension_entree_7_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_7_tension_entree_7_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_7_tension_entree_7_is_in_range(uint16_t value);

/**
 * Pack message Entree_Analogique_6.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_6_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_6_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_6.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_6_unpack(
    struct ana_inputs_muxtrace_entree_analogique_6_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_6.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_6_init(struct ana_inputs_muxtrace_entree_analogique_6_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_6_tension_entree_6_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_6_tension_entree_6_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_6_tension_entree_6_is_in_range(uint16_t value);

/**
 * Pack message Entree_Analogique_5.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_5_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_5_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_5.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_5_unpack(
    struct ana_inputs_muxtrace_entree_analogique_5_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_5.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_5_init(struct ana_inputs_muxtrace_entree_analogique_5_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_5_tension_entree_5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_5_tension_entree_5_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_5_tension_entree_5_is_in_range(uint16_t value);

/**
 * Pack message Entree_Analogique_4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_4_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_4_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_4_unpack(
    struct ana_inputs_muxtrace_entree_analogique_4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_4_init(struct ana_inputs_muxtrace_entree_analogique_4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_4_tension_entree_4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_4_tension_entree_4_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_4_tension_entree_4_is_in_range(uint16_t value);

/**
 * Pack message Entree_Analogique_3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_3_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_3_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_3_unpack(
    struct ana_inputs_muxtrace_entree_analogique_3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_3_init(struct ana_inputs_muxtrace_entree_analogique_3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_3_tension_entree_3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_3_tension_entree_3_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_3_tension_entree_3_is_in_range(uint16_t value);

/**
 * Pack message Entree_Analogique_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_2_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_2_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_2_unpack(
    struct ana_inputs_muxtrace_entree_analogique_2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_2_init(struct ana_inputs_muxtrace_entree_analogique_2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_2_tension_entree_2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_2_tension_entree_2_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_2_tension_entree_2_is_in_range(uint16_t value);

/**
 * Pack message Entree_Analogique_1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_1_pack(
    uint8_t *dst_p,
    const struct ana_inputs_muxtrace_entree_analogique_1_t *src_p,
    size_t size);

/**
 * Unpack message Entree_Analogique_1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ana_inputs_muxtrace_entree_analogique_1_unpack(
    struct ana_inputs_muxtrace_entree_analogique_1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Entree_Analogique_1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ana_inputs_muxtrace_entree_analogique_1_init(struct ana_inputs_muxtrace_entree_analogique_1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ana_inputs_muxtrace_entree_analogique_1_tension_entree_1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ana_inputs_muxtrace_entree_analogique_1_tension_entree_1_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ana_inputs_muxtrace_entree_analogique_1_tension_entree_1_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
