/**
 * @file base_de_donnee_can_he3000.c
 *
 * @brief This source file was generated by cantools version 40.7.1 Thu Nov  6 15:19:19 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "base_de_donnee_can_he3000.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int base_de_donnee_can_he3000_info_1_pack(
    uint8_t *dst_p,
    const struct base_de_donnee_can_he3000_info_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->vehicle_speed, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->vehicle_speed, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u32(src_p->total_odometer, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->total_odometer, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->total_odometer, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->total_odometer, 24u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->controller_status, 0u, 0x03u);
    dst_p[7] |= pack_left_shift_u8(src_p->bdi_percentage, 0u, 0xffu);

    return (8);
}

int base_de_donnee_can_he3000_info_1_unpack(
    struct base_de_donnee_can_he3000_info_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->vehicle_speed = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->vehicle_speed |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->total_odometer = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    dst_p->total_odometer |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    dst_p->total_odometer |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    dst_p->total_odometer |= unpack_left_shift_u32(src_p[5], 24u, 0xffu);
    dst_p->controller_status = unpack_right_shift_u8(src_p[6], 0u, 0x03u);
    dst_p->bdi_percentage = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int base_de_donnee_can_he3000_info_1_init(struct base_de_donnee_can_he3000_info_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct base_de_donnee_can_he3000_info_1_t));

    return 0;
}

uint16_t base_de_donnee_can_he3000_info_1_vehicle_speed_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double base_de_donnee_can_he3000_info_1_vehicle_speed_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool base_de_donnee_can_he3000_info_1_vehicle_speed_is_in_range(uint16_t value)
{
    return (value <= 32760u);
}

uint32_t base_de_donnee_can_he3000_info_1_total_odometer_encode(double value)
{
    return (uint32_t)(value / 0.1);
}

double base_de_donnee_can_he3000_info_1_total_odometer_decode(uint32_t value)
{
    return ((double)value * 0.1);
}

bool base_de_donnee_can_he3000_info_1_total_odometer_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint8_t base_de_donnee_can_he3000_info_1_controller_status_encode(double value)
{
    return (uint8_t)(value);
}

double base_de_donnee_can_he3000_info_1_controller_status_decode(uint8_t value)
{
    return ((double)value);
}

bool base_de_donnee_can_he3000_info_1_controller_status_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

uint8_t base_de_donnee_can_he3000_info_1_bdi_percentage_encode(double value)
{
    return (uint8_t)(value);
}

double base_de_donnee_can_he3000_info_1_bdi_percentage_decode(uint8_t value)
{
    return ((double)value);
}

bool base_de_donnee_can_he3000_info_1_bdi_percentage_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

int base_de_donnee_can_he3000_info_3_pack(
    uint8_t *dst_p,
    const struct base_de_donnee_can_he3000_info_3_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->reset_partial_odometer, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->can_low_batt_flag, 6u, 0x40u);

    return (1);
}

int base_de_donnee_can_he3000_info_3_unpack(
    struct base_de_donnee_can_he3000_info_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->reset_partial_odometer = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->can_low_batt_flag = unpack_right_shift_u8(src_p[0], 6u, 0x40u);

    return (0);
}

int base_de_donnee_can_he3000_info_3_init(struct base_de_donnee_can_he3000_info_3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct base_de_donnee_can_he3000_info_3_t));

    return 0;
}

uint8_t base_de_donnee_can_he3000_info_3_reset_partial_odometer_encode(double value)
{
    return (uint8_t)(value);
}

double base_de_donnee_can_he3000_info_3_reset_partial_odometer_decode(uint8_t value)
{
    return ((double)value);
}

bool base_de_donnee_can_he3000_info_3_reset_partial_odometer_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

uint8_t base_de_donnee_can_he3000_info_3_can_low_batt_flag_encode(double value)
{
    return (uint8_t)(value);
}

double base_de_donnee_can_he3000_info_3_can_low_batt_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool base_de_donnee_can_he3000_info_3_can_low_batt_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int base_de_donnee_can_he3000_info_5_pack(
    uint8_t *dst_p,
    const struct base_de_donnee_can_he3000_info_5_t *src_p,
    size_t size)
{
    uint16_t vehicle_acceleration;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    vehicle_acceleration = (uint16_t)src_p->vehicle_acceleration;
    dst_p[0] |= pack_left_shift_u16(vehicle_acceleration, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(vehicle_acceleration, 8u, 0xffu);

    return (2);
}

int base_de_donnee_can_he3000_info_5_unpack(
    struct base_de_donnee_can_he3000_info_5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t vehicle_acceleration;

    if (size < 2u) {
        return (-EINVAL);
    }

    vehicle_acceleration = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    vehicle_acceleration |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->vehicle_acceleration = (int16_t)vehicle_acceleration;

    return (0);
}

int base_de_donnee_can_he3000_info_5_init(struct base_de_donnee_can_he3000_info_5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct base_de_donnee_can_he3000_info_5_t));

    return 0;
}

int16_t base_de_donnee_can_he3000_info_5_vehicle_acceleration_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double base_de_donnee_can_he3000_info_5_vehicle_acceleration_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool base_de_donnee_can_he3000_info_5_vehicle_acceleration_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 1000));
}

int base_de_donnee_can_he3000_info_2_pack(
    uint8_t *dst_p,
    const struct base_de_donnee_can_he3000_info_2_t *src_p,
    size_t size)
{
    uint16_t frequency;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->trip_odometer, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->trip_odometer, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->keyswitch_voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->keyswitch_voltage, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->current_rms, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->current_rms, 8u, 0xffu);
    frequency = (uint16_t)src_p->frequency;
    dst_p[6] |= pack_left_shift_u16(frequency, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(frequency, 8u, 0xffu);

    return (8);
}

int base_de_donnee_can_he3000_info_2_unpack(
    struct base_de_donnee_can_he3000_info_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t frequency;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->trip_odometer = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->trip_odometer |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->keyswitch_voltage = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->keyswitch_voltage |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_rms = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->current_rms |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    frequency = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    frequency |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->frequency = (int16_t)frequency;

    return (0);
}

int base_de_donnee_can_he3000_info_2_init(struct base_de_donnee_can_he3000_info_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct base_de_donnee_can_he3000_info_2_t));

    return 0;
}

uint16_t base_de_donnee_can_he3000_info_2_trip_odometer_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double base_de_donnee_can_he3000_info_2_trip_odometer_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool base_de_donnee_can_he3000_info_2_trip_odometer_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

uint16_t base_de_donnee_can_he3000_info_2_keyswitch_voltage_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double base_de_donnee_can_he3000_info_2_keyswitch_voltage_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool base_de_donnee_can_he3000_info_2_keyswitch_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t base_de_donnee_can_he3000_info_2_current_rms_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double base_de_donnee_can_he3000_info_2_current_rms_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool base_de_donnee_can_he3000_info_2_current_rms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t base_de_donnee_can_he3000_info_2_frequency_encode(double value)
{
    return (int16_t)(value);
}

double base_de_donnee_can_he3000_info_2_frequency_decode(int16_t value)
{
    return ((double)value);
}

bool base_de_donnee_can_he3000_info_2_frequency_is_in_range(int16_t value)
{
    return ((value >= -18000) && (value <= 18000));
}

int base_de_donnee_can_he3000_info_4_pack(
    uint8_t *dst_p,
    const struct base_de_donnee_can_he3000_info_4_t *src_p,
    size_t size)
{
    uint16_t batt_current;
    uint16_t battery_power;
    uint16_t motor_rpm;
    uint16_t motor_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    battery_power = (uint16_t)src_p->battery_power;
    dst_p[0] |= pack_left_shift_u16(battery_power, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(battery_power, 8u, 0xffu);
    motor_rpm = (uint16_t)src_p->motor_rpm;
    dst_p[2] |= pack_left_shift_u16(motor_rpm, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(motor_rpm, 8u, 0xffu);
    motor_temp = (uint16_t)src_p->motor_temp;
    dst_p[4] |= pack_left_shift_u16(motor_temp, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(motor_temp, 8u, 0xffu);
    batt_current = (uint16_t)src_p->batt_current;
    dst_p[6] |= pack_left_shift_u16(batt_current, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(batt_current, 8u, 0xffu);

    return (8);
}

int base_de_donnee_can_he3000_info_4_unpack(
    struct base_de_donnee_can_he3000_info_4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t batt_current;
    uint16_t battery_power;
    uint16_t motor_rpm;
    uint16_t motor_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    battery_power = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    battery_power |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->battery_power = (int16_t)battery_power;
    motor_rpm = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    motor_rpm |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->motor_rpm = (int16_t)motor_rpm;
    motor_temp = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    motor_temp |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->motor_temp = (int16_t)motor_temp;
    batt_current = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    batt_current |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->batt_current = (int16_t)batt_current;

    return (0);
}

int base_de_donnee_can_he3000_info_4_init(struct base_de_donnee_can_he3000_info_4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct base_de_donnee_can_he3000_info_4_t));

    return 0;
}

int16_t base_de_donnee_can_he3000_info_4_battery_power_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double base_de_donnee_can_he3000_info_4_battery_power_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool base_de_donnee_can_he3000_info_4_battery_power_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t base_de_donnee_can_he3000_info_4_motor_rpm_encode(double value)
{
    return (int16_t)(value);
}

double base_de_donnee_can_he3000_info_4_motor_rpm_decode(int16_t value)
{
    return ((double)value);
}

bool base_de_donnee_can_he3000_info_4_motor_rpm_is_in_range(int16_t value)
{
    return ((value >= -12000) && (value <= 12000));
}

int16_t base_de_donnee_can_he3000_info_4_motor_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double base_de_donnee_can_he3000_info_4_motor_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool base_de_donnee_can_he3000_info_4_motor_temp_is_in_range(int16_t value)
{
    return ((value >= -10000) && (value <= 30000));
}

int16_t base_de_donnee_can_he3000_info_4_batt_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double base_de_donnee_can_he3000_info_4_batt_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool base_de_donnee_can_he3000_info_4_batt_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int base_de_donnee_can_he3000_trame_contact_pack(
    uint8_t *dst_p,
    const struct base_de_donnee_can_he3000_trame_contact_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    return (8);
}

int base_de_donnee_can_he3000_trame_contact_unpack(
    struct base_de_donnee_can_he3000_trame_contact_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    return (0);
}

int base_de_donnee_can_he3000_trame_contact_init(struct base_de_donnee_can_he3000_trame_contact_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct base_de_donnee_can_he3000_trame_contact_t));

    return 0;
}
